project_id = "aldtcudqvbhmngkstbrr"

[functions.register-worker]
verify_jwt = false

[functions.register-establishment]
verify_jwt = false

[functions.register-department]
verify_jwt = false

[functions.submit-attendance]
verify_jwt = false
